#
# Github Workflow config file
#
# - reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# - composite actions: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
#

#
# see [repo-visualizer](https://github.com/githubocto/repo-visualizer)
#

name: core-repo-diagram

on:
  push:
    paths:
      - '.github/actions/**/*'
      - '.github/workflows/core-repo-diagram-workflow.yml'
      - '**/package.json'
      - '**/package-lock.json'
      - '**/yarn.lock'
      - 'packages/core-*/**/*'
    branches:
      - dev
      - master
      - release
  workflow_dispatch:

env:
  #
  # Debugging
  #
  DEBUG: 'nr*'
  #
  # Node
  #
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          clean: false

      - name: 'Checkout, Setup NodeJS + yarn and install dependencies'
        uses: ./.github/actions/base-node-setup

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          commit_message: 'chore(core): update diagram'
          output_file: 'docs/assets/images/core-repo-diagram.svg'
          excluded_globs: '(./)?**/node_modules/**/*;(./)?**/dist/**/*;(./)?**/lib/**/*;(./)?**/built/**/*;(./)?**/public/**/*;(./)?**/.cache/**/*'
          excluded_paths: 'node_modules,dist,lib,built,.cache,public,out,build,.yarn,.vscode,package-lock.json,yarn.lock'
