#
# Github Action
#
# see https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/creating-a-javascript-action
# see https://docs.github.com/en/free-pro-team@latest/actions/creating-actions/metadata-syntax-for-github-actions
# see https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
#



name: 'Checkout, Setup NodeJS and install dependencies'
description: 'Basic steps to setup a build with NodeJS and npm'
runs:
    using: "composite"
    steps:
      - name: Inject Github slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      #
      # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
      # Otherwise, clone it normally.
      #

      #
      # Note: if is not supported yet, see https://github.com/actions/runner/issues/834
      # Enable below when it is
      #

      # - name: Checkout
      #   if: ${{ github.event_name != 'pull_request_target' }}
      #   uses: actions/checkout@v2
      #   with:
      #     clean: false

      # - name: Checkout PR
      #   if: ${{ github.event_name == 'pull_request_target' }}
      #   uses: actions/checkout@v2
      #   with:
      #     ref: ${{ github.event.pull_request.head.sha }}
      #     clean: false

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          architecture: 'x64'

      - name: Print NodeJS version
        run: node -v
        shell: bash

      - name: Check NodeJS Options
        run: echo $NODE_OPTIONS && node -e 'console.log(`node heap limit = ${require("v8").getHeapStatistics().heap_size_limit / (1024 * 1024)} Mb`)'
        shell: bash

      - name: Set npm cache location
        run: npm config set cache $(pwd)/../.npm-cache
        shell: bash

      - name: Print npm configuration
        run: npm config list
        shell: bash

      - name: Install dependencies and build core packages
        run: npm ci --legacy-peer-deps
        shell: bash


