#
# Github Workflow config file
#
# - reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# - composite actions: https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
#

name: cli

on:
  push:
    paths:
      - '.github/actions/**/*'
      - '.github/workflows/cli-workflow.yml'
      - '**/package.json'
      - '**/package-lock.json'
      - '**/yarn.lock'
      - 'packages/**/*'
    branches:
      - dev
      - master
      - release
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_target:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

env:
  #
  # Debugging
  #
  DEBUG: 'condohub*'
  #
  # Node
  #
  NODE_OPTIONS: '--max-old-space-size=4096'

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    # If the PR is coming from a fork (pull_request_target), ensure it's opened by "dependabot[bot]".
    # Otherwise, clone it normally.
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name != 'pull_request_target' && github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          clean: false

      - name: 'Checkout, Setup NodeJS and install dependencies'
        uses: ./.github/actions/base-node-setup

      - name: Verify dependencies
        run: yarn lerna:depcheck -- --scope @condohub/cli

      - name: Typecheck
        run: yarn lerna:typecheck -- --scope @condohub/cli

      - name: Lint (ls-lint) source files
        run: yarn lerna:ls-lint -- --scope @condohub/cli

      - name: Lint source files
        run: npm exec eslint -- ./packages/cli/src/ --ext "ts,tsx"

      - name: Run unit tests
        run: yarn lerna:test -- --scope @condohub/cli
